### PR TITLE
added commands kill, rm, rmi

### PR DESCRIPTION
**Pull request by andmoos**
Hi I've added some commands to enable crowdr to allow me cleaning up after myself durign development.

Also fixed that docker build is called even for containers which are not configured so (e.g. when only image source is configured)

### CODE REVIEW

**Comment by polonskiy** [comment]
Thanks! :+1:

**Comment by polonskiy** [comment]
Also, what is your use case for the `rm` command? It will throw errors for the running containers.

**Comment by polonskiy** [comment]
Merged. Thanks. :+1:

**Comment by andmoos** [comment]
have been quite busy the last weeks, sorry for not responding. Thank you for merging

**Pull request closed without merging**
