### PR TITLE
Update of documentation

### PR DESCRIPTION
**Pull request by marcinwaldowski**
Please review the update of documentation.

Please note that I still need to:
- check the examples (`crowdr ip` doesn't work for me for first example),
- provide quick-start guide for docker <1.9.

### CODE REVIEW

**Comment by polonskiy** [comment]
Wow! Thank you so much!
:+1: :+1: :+1:

**Comment by polonskiy** [comment]
`crowdr ip` shows ip for default bridge network. Custom networks are not supported at this moment.

**Comment by polonskiy** [comment]
> provide quick-start guide for docker <1.9

Docker is moving very fast. I mean current stable docker version is broken in some way :smile: and older versions are broken even more :smile: . I think, at this point, older versions support is not worth it. Maybe with more mature docker versions and bigger crowdr community it became one of the priorities of this project but not yet.

Anyway, any help in this direction is highly appreciated.

@byrnedo @coderofsalvation @superm00s

**Comment by marcinwaldowski** [comment]
Thanks for merging.

**Pull request merged**
