### PR TITLE
Local Dockerfile build dependency order

### PR DESCRIPTION
**Pull request by andmoos**
Hi, 
i've added parsing and honoring local build dependency order during e.g. 'build' and 'rmi' from Dockerfile's FROM option.

Looks this useful to you?

### CODE REVIEW

**Comment by polonskiy** [comment]
Hmm. What is the use case for that?

**Comment by andmoos** [comment]
My use-case was that a shared 'base' image needs to be build before the derived ones. 
This applies to the 'rmi' command as well, but here in reverse order. 

It may not fit to the 'docker-way' - but here it seems that all solutions not using docker hub are not pretty well supported. Not wanting any repository infrastructure was the main argument for crowdr in the first place. At least for the docker use i care about.

**Comment by polonskiy** [comment]
Could you please show your `crowdr.cfg.sh` and `Dockerfile`?

**Comment by coderofsalvation** [comment]
This sounds like a case which already could be solved by a `hooks/build.before` and `hooks/rmi.before` script.
Crowdr would execute it when invoking `crowdr build` and `crowdr rmi` before building the images.
Any crowdr command can be patched by hooks, see the hooks section in README.md

**Pull request closed without merging**
