### PR TITLE
Ordering from config. Container hooks.

### PR DESCRIPTION
**Pull request by polonskiy**
Based on #8 #10 

I have changed container hooks naming.
I think format `redis hook run.after sleep 5` is too confusing. Run after sleep?
Changed to `redis after.run sleep 5`.

I know. It is inconsistent with global hooks.

Any comments?
@coderofsalvation @byrnedo @marcinwaldowski

### CODE REVIEW

**Comment by byrnedo** [comment]
Good point. I agree with you.

**Comment by marcinwaldowski** [comment]
:+1: 

Ordering from config is ok for me, I like it better than ordering extracted from links.
Container hooks naming is fine for me. I tested run hook and it worked for me.

Two questions:
1. Are we going to implement hooks for start, stop and restart? 
2. I want to implement bash function and use it in more than one container hook. Is it possible? Where should I put the body of that function?

**Comment by byrnedo** [comment]
Answer to 2: you can pass the path to a file as the hook, so that will let
you reuse

```
app hook before.run ./my-script.sh
```

**Comment by marcinwaldowski** [comment]
Thanks :)

**Pull request merged**
